 CREATE TABLE words_en (id INT NOT NULL AUTO_INCREMENT, word  VARCHAR(32) CHARACTER SET utf8 COLLATE utf8_bin , PRIMARY KEY (id) );
 CREATE TABLE words_ru (id INT NOT NULL AUTO_INCREMENT, word  VARCHAR(32) CHARACTER SET utf8 COLLATE utf8_bin , PRIMARY KEY (id) );
 CREATE TABLE ru2en ( idRu INT , idEn INT);
